name: Ma super CI/CD

on:
  push:
   branches: [ main ]


jobs:
#je donne un nom
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: installation des dépendence
        run: npm install

      - name: lancement des tests
        run: npm run test

      - name: Build de l'appli
        run : npm run build

      - name: Upload du dossier dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps: 
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Download du dossier dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: test du dist
        run: ls -la ./dist  

      - name: Deploiement en github page
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
